[package]
name = "statorius"
version = "0.2.0"
edition = "2024"

[profile.release]
lto = true          # Link Time Optimization: merges all crates into one unit
codegen-units = 1   # Reduces parallel compilation to allow more aggressive optimizations
panic = "abort"     # Removes stack unwinding code (saves a lot of space)
strip = true        # Automatically strips symbols from the binary

[dependencies]
eframe = "0.35" # GUI framework
tokio = { version = "1", features = ["full"] } # Async runtime
surge-ping = "0.9" # Async ICMP
# Useful for retrieving local IPs
default-net = "0.22"