// Release builds have no console window at all - both the GUI and the
// re-exec'd `--l2-helper` process (it's the same binary) would otherwise
// each get one from Windows, and the helper's has to stay open for as long
// as L2 mode is active. Left as the default (console-subsystem) in debug
// builds, so `cargo run`'s stdout/stderr still show up somewhere.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod net;
mod state;

use app::StatoriusApp;
use state::SharedState;
use tokio::sync::mpsc;

// 256x256 RGBA PNG, generated at build time from ico/statorius-master.png
// (see build.rs) - reused for both the native window/taskbar icon and the
// About tab's texture, decoded once below. The Windows .exe icon shown in
// Explorer/shortcuts is a separate asset (also generated by build.rs, but
// as a multi-resolution .ico embedded directly as a PE resource) since
// that one needs several baked-in resolutions rather than a single RGBA
// buffer.
static APP_ICON_PNG: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/statorius-icon.png"));

#[tokio::main]
async fn main() -> eframe::Result<()> {
    // Dual-mode binary: `statorius --l2-helper <endpoint>` is not the
    // GUI at all - it's the (possibly elevated) L2 helper process, spawned
    // by `net::l2_manager` when the user checks "L2 mode". This is checked
    // before touching anything GUI-related, since the helper never opens a
    // window.
    let args: Vec<String> = std::env::args().collect();
    if let Some(pos) = args.iter().position(|a| a == "--l2-helper") {
        match args.get(pos + 1) {
            Some(endpoint) => net::l2_helper::run_l2_helper(endpoint.clone()).await,
            None => eprintln!("--l2-helper requires an endpoint name argument"),
        }
        return Ok(());
    }

    // Commands (Start/Stop/Delete) flow UI -> worker over this channel.
    let (tx_req, rx_req) = mpsc::channel::<state::WorkerCommand>(100);

    // Results flow worker -> UI through shared state instead of a channel:
    // the worker writes into it, the UI reads a snapshot every frame.
    let shared_state = SharedState::new();

    tokio::spawn(net::ping_worker(rx_req, shared_state.clone()));

    // One-time, side-effect-free check of whether raw L2 work is already
    // possible as launched - never tries to acquire privileges itself. See
    // `net::l2` for what's actually being checked, and how "impossible
    // outright" is told apart from "possible but needs elevation".
    let l2_readiness = net::l2::probe_l2_readiness();

    // Same shared-state pattern as ping: the UI only ever sends L2Command
    // and reads SharedL2Status. The manager task owns spawning the helper
    // (elevated or not), the IPC handshake, and its whole lifecycle - the
    // GUI process itself never touches a raw socket.
    let (tx_l2, rx_l2) = mpsc::channel::<net::l2_manager::L2Command>(8);
    let l2_status = net::l2_manager::SharedL2Status::new();

    // Captured DHCP exchanges, for the "DHCP" tab. Same shared-state shape
    // as everything else here: `l2_manager` writes into it as unsolicited
    // `L2Message::DhcpEvent`s arrive from the helper's passive sniffer, the
    // UI only ever reads a snapshot.
    let dhcp_state = net::dhcp_state::DhcpState::new();

    // Separate channel for anything that actually wants to *use* L2 once
    // it's active (ping/duplicate-check jobs) - today that's only the L2
    // pinger list below, but it's the same channel a future TCP/UDP L2 scan
    // would use too. The manager only ever forwards these to the helper
    // while a session is Active; otherwise they fail immediately.
    let (tx_l2_jobs, rx_l2_jobs) = mpsc::channel::<net::l2_manager::L2JobRequest>(32);

    tokio::spawn(net::l2_manager::l2_manager_task(
        rx_l2,
        rx_l2_jobs,
        l2_status.clone(),
        l2_readiness.clone(),
        dhcp_state.clone(),
    ));

    // The L2 pinger list itself: same Start/Stop/Delete + shared-state
    // pattern as the plain ping list, just driven over raw L2 instead of
    // regular sockets. The app also gets its own clone of `tx_l2_jobs`
    // directly, to run the live duplicate-check on whatever's currently
    // typed into the "add target" form, independent of any tracked target.
    let (tx_l2_pinger, rx_l2_pinger) = mpsc::channel::<net::l2_pinger::L2PingerCommand>(100);
    let l2_pinger_state = net::l2_pinger::L2PingerState::new();
    tokio::spawn(net::l2_pinger::l2_pinger_worker(
        rx_l2_pinger,
        l2_pinger_state.clone(),
        tx_l2_jobs.clone(),
    ));

    // System DNS servers, for the "DNS Servers" tab, plus on-demand
    // hostname resolution against whichever of them the user checks - see
    // `net::dns`. `dns_shared` is read fresh every frame (same shared-state
    // shape as `l2_status`/`dhcp_state`); `tx_dns` carries one-off resolve
    // requests the Ping tab sends when Enter is pressed on something that
    // isn't already a literal IP address.
    let (tx_dns, rx_dns) = mpsc::channel::<net::dns::DnsCommand>(16);
    let dns_shared = net::dns::SharedDnsServers::new();
    tokio::spawn(net::dns::dns_worker(rx_dns, dns_shared.clone()));

    let icon_data = eframe::icon_data::from_png_bytes(APP_ICON_PNG)
        .expect("embedded app icon (ico/statorius-icon.png) is not a valid PNG");

    let mut options = eframe::NativeOptions::default();
    options.viewport = options.viewport.with_icon(icon_data.clone());

    eframe::run_native(
        "Statorius",
        options,
        Box::new(move |cc| {
            // Same decoded RGBA buffer as the window icon above, uploaded
            // once as a GPU texture here (rather than re-decoding the PNG)
            // for the About tab to render at a smaller display size.
            let color_image = eframe::egui::ColorImage::from_rgba_unmultiplied(
                [icon_data.width as usize, icon_data.height as usize],
                &icon_data.rgba,
            );
            let app_icon_texture = cc.egui_ctx.load_texture(
                "app-icon",
                color_image,
                eframe::egui::TextureOptions::default(),
            );

            Ok(Box::new(StatoriusApp::new(
                tx_req,
                shared_state,
                l2_readiness,
                tx_l2,
                l2_status,
                tx_l2_pinger,
                l2_pinger_state,
                tx_l2_jobs,
                dhcp_state,
                dns_shared,
                tx_dns,
                app_icon_texture,
            )))
        }),
    )
}